import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./frontend/*.html",
    "./frontend/*.js",
    "./backend/routes/**/*.js",
    "./backend/lib/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#735c00",
        "background": "#ffffff",
        "on-secondary-container": "#636260",
        "tertiary-fixed": "#ffe088",
        "surface-dim": "#dcd9d9",
        "primary-fixed-dim": "#a5d0b9",
        "on-secondary-fixed": "#1c1c1a",
        "outline-variant": "#c1c8c2",
        "surface-bright": "#ffffff",
        "tertiary-fixed-dim": "#e9c349",
        "secondary-fixed-dim": "#c8c6c3",
        "secondary-fixed": "#e5e2df",
        "primary-fixed": "#c1ecd4",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary-fixed-variant": "#274e3d",
        "surface": "#ffffff",
        "on-primary-fixed": "#002114",
        "on-error-container": "#93000a",
        "secondary-container": "#e2dfdc",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#4e3d00",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#474745",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#303030",
        "on-background": "#1b1c1c",
        "primary": "#012d1d",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f2",
        "surface-variant": "#e4e2e1",
        "tertiary-container": "#cba72f",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-container": "#86af99",
        "inverse-primary": "#a5d0b9",
        "on-surface-variant": "#414844",
        "surface-tint": "#3f6653",
        "primary-container": "#1b4332",
        "inverse-on-surface": "#f3f0f0",
        "outline": "#717973",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "secondary": "#5f5e5c",
        "surface-container-highest": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-tertiary-fixed": "#241a00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        lg: "56px",
        "container-max": "1760px",
        gutter: "32px",
        md: "40px",
        sm: "12px",
        xl: "120px",
      },
      fontFamily: {
        h1: ["Plus Jakarta Sans"],
        h2: ["Plus Jakarta Sans"],
        h3: ["Plus Jakarta Sans"],
        "body-md": ["Lexend"],
        "body-lg": ["Lexend"],
        "label-caps": ["Lexend"],
      },
      fontSize: {
        h1: ["68px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "700" }],
        h2: ["50px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
        h3: ["32px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["19px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["23px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["16px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
